version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chatfila
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
